### ISSUE TITLE
Domoticz Scenes not logging into Domoticz

### ISSUE THREAD

**Issue by user8446** [Paul-VW/script.domoticz.scenes#6]
Hello,

I am trying to connect Domoticz Scenes to Domoticz (v2021.1). I continually get a "Domoticz Scenes error - Check the log for more information.". However, there is nothing in the Kodi log. 

I have tried:
1. Using the Domoticz https port and http port
2. Using the admin account and normal user account
3. Tried with and without http in front of the Domoticz IP
4. With Basic-Auth selected for Authentication in Domoticz  I'll get an entry in the log that the login failed from [kodi ip address]
5. With Login Page selected for Authentication in Domoticz I get nothing in the log

Any recommendations on which way to go from here to debug?
Thank you

**Comment by user8446** [comment]
@Paul-VW 
Update: The bug appears to be an authentication issue with the addon logging into Domoticz. If I add the Kodi IP to the local networks IP in Domoticz where no username & password is needed, it works (http).
SSL doesn't work at all even with no username/password.

I looked at the code but not familiar w/ python so nothing stood out otherwise I would have done a PR :)

**Comment by jiemeb** [comment]
Same issue

**Comment by user8446** [comment]
Hi @Paul-VW just updating that the issue still persists on Domoticz version 2022.2. Any direction for me to test or try?

**Comment by Paul-VW** [comment]
Should be solved in 0.0.20

**Comment by user8446** [comment]
Great! Thank you @Paul-VW

**Comment by user8446** [comment]
Hi I added the new files in a zip and the add-on did upgrade. However, on my end I still have the same issue where I could not login in Domoticz without putting the Kodi IP in trusted networks and removing the username & password. 

Can someone else please try to make sure I didn't make a mistake somewhere on my end?

**Comment by Paul-VW** [comment]
Please make sure that in Domoticz you've enabled basic auth:
Setup>>Settings>>Security>>API Protection

**Comment by user8446** [comment]
Ok I toggled the basic auth on but still no login unless the username & pw is removed and I add the IP address as a trusted network in Domoticz (no username or pw).

However, I'm not sure if there is an error of my doing on the upgrade as when I change scenes I get this in the Domoticz log:

`[WebServer] Deprecated RType (scenes) for API request. Handled via fallback (getscenes), please use correct API Command!`

Wouldn't that have been fixed in https://github.com/Paul-VW/script.domoticz.scenes/issues/8 ?

**Comment by Paul-VW** [comment]
Ok, I figured out what went wrong. For some reason Domoticz 2023.2 returns the same revision as 2023.1 (Rev 15453), where that should have been 15457. Therefore the wrong requests where made. 

Just posted an updated version. Please try that one (still requires basic auth. Trusted network shouldn't be necessary)

**Comment by user8446** [comment]
Hi it's still not logging in. From what I can tell it appears that the API call isn't putting the basic auth in the header correctly ( https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Authorization ). 

For example, I tried the API call in PowerShell and browser it doesn't login but with cURL it does. Both return `200 OK` though:

```
Invoke-WebRequest -SkipCertificateCheck -Uri "https://user:password@#.#.#.#:443/json.htm?type=command&param=getversion"

StatusCode        : 200
StatusDescription : OK
Content           : {
                        "status" : "OK",
                        "title" : "GetVersion"
                    }

RawContent        : HTTP/1.1 200 OK
                    Cache-Control: no-cache
                    Pragma: no-cache
                    Access-Control-Allow-Origin: *
                    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
                    X-Content-Type-Options: nosniff
                    Co…
Headers           : {[Cache-Control, System.String[]], [Pragma, System.String[]], [Access-Control-Allow-Origin, System.String[]],
                    [Strict-Transport-Security, System.String[]]…}
Images            : {}
InputFields       : {}
Links             : {}
RawContentLength  : 46
RelationLink      : {}
```

```
curl --insecure --url "https://user:password@#.#.#.#:443/json.htm?type=command&param=getversion"

{
        "HaveUpdate" : false,
        "UseUpdate" : false,
        "build_time" : "2023-07-22 04:39:06",
        "dzvents_version" : "3.1.8",
        "hash" : "25624ca14",
        "python_version" : "None",
        "status" : "OK",
        "title" : "GetVersion",
        "version" : "2023.2 (build 15457)"
}
```

**Comment by Paul-VW** [comment]
This seems not to be related to the Domoticz version, but to the SSL-connection. An error is raised for the API-call over requests. Not yet sure why though. Are you able to connect over http protocol? That should work fine with both Domoticz 2023.1 and 2023.2

**Comment by user8446** [comment]
I just tried the call via http and the result was the same. Works with cURL and not with PowerShell so I think it's narrowing down to the basic auth header.

Don't know Python but I researched and found this for basic auth: https://requests.readthedocs.io/en/latest/user/authentication/

So instead of: `url = protocol + usr + ":" + pwd + "@" + server + ":" + str(port) + "/json.htm?" + query`

Maybe: `url = protocol + server + ":" + str(port) + "/json.htm?" + query`

`r = requests.get(url=url, auth=('usr', 'pwd'), verify=False)`

**Comment by Paul-VW** [comment]
> I just tried the call via http and the result was the same. Works with cURL and not with PowerShell so I think it's narrowing down to the basic auth header.
> 
> Don't know Python but I researched and found this for basic auth: https://requests.readthedocs.io/en/latest/user/authentication/
> 
> So instead of: `url = protocol + usr + ":" + pwd + "@" + server + ":" + str(port) + "/json.htm?" + query`
> 
> Maybe: `url = protocol + server + ":" + str(port) + "/json.htm?" + query`
> 
> `r = requests.get(url=url, auth=('usr', 'pwd'), verify=False)`

Did some testing and that does seem to do the trick. I'll try to get this fix implemented later today

**Comment by Paul-VW** [comment]
Should be resolved now. Found some other issues with the connection as well that are now solved. Please try again

**Comment by user8446** [comment]
Unfortunately still doesn't login on my end, it's working for you? I will continue to try to debug.

 I can confirm that the deprecated API errors are gone though.

**Comment by Paul-VW** [comment]
I can log in properly on both 2023.1 and 2023.2 with and without SSL and without adding to trusted network. Basic auth does need to be enabled though within Domoticz. Can you please check the kodi.log for errors that might show up ?

**Comment by user8446** [comment]
I checked and nothing in the logs which is what is expected when the basic auth header is missing. I tried with and without SSL. Basic auth is enabled, trusted networks not added. Adding the trusted networks still logs in as before.

I don't think it should make a difference but I am not on the same box for Kodi and Domoticz. Are you on the same box? I'm wondering if localhost might have additional privileges.

**Comment by Paul-VW** [comment]
Did you select an item that contains switches / groups / scenes? If you select favourites while no devices or groups/scenes are set as a favourite, no data is returned which will result in an error. Please also check if you're supplying the proper credentials and are using an account with enough permissions. I've never tested it with anything else but admin, but I'd think that even Viewer might be enough. Might be something silly like that. 

It shouldn't matter where you connect from, as long as you can reach the service. I'm connecting succesfully to Domoticz 2023.1 and 2023.2 on localhost, on LAN and from WAN and from anywhere, and works perfectly fine, as long as you're able to reach the web interface on that specific port and protocol.

**Comment by user8446** [comment]
I'm only using scenes and it does work as expected when set as a trusted network so functionality is working as expected. It's just the login. I did try both user and admin. Not sure why it's not working on my end. @jiemeb are you able to test on your end?

**Comment by Paul-VW** [comment]
@user8446 If authentication is failing (so the service is reachable, it just doesn't allow you access), I would expect that you'll find a log entry in kodi.log with KeyError: 'Revision'

Since you don't see that happen, it is to be expected that there is succesfully connected to Domoticz, but there is simply no data to show

**Comment by user8446** [comment]
From my testing connecting with CLI, it's seems to still be failing with the format still and not a user/pw auth fail. Not sure why it's working for you and not on my end so I will continue to investigate... thank you for the time you have put into this.

**Comment by Paul-VW** [comment]
Unfortunately i'm not able to replicate the issue and therefore cannot resolve it at this time. I'll do some more testing from my end as well to see if I can replicate it to investigate

**Comment by user8446** [comment]
Ok I've been researching and read [this](https://stackoverflow.com/questions/18139093/base64-authentication-python) and changed lines 58 & 63 from:

`r = requests.get(url=url, auth=(usr, pwd), verify=False)`

to:

`r = requests.get(url=url, auth=HTTPBasicAuth(usr, pwd), verify=False)`

and it is now working correctly with both http and SSL on my end. Trusted networks is not set and the user rights did have to be set to admin. I'm not sure if it makes a difference but I am on Kodi 20.2 on Android.

**Comment by Paul-VW** [comment]
Tested this and seems to work fine, so fi this solves it for you as well, then I'd say the issue is fixed then 👍

**Comment by user8446** [comment]
Great would it help you if I did a PR?

Edit: Nevermind you beat me to it! :)
